fields:
  tracking_id:
    type: text
    validate: required
    width: 100
  async:
    type: toggle
  track_uid:
    type: toggle
  beacon:
    type: toggle
  display_features:
    type: toggle
  link_id:
    type: toggle
  ignore_admins:
    type: toggle
  